[package]
license = ["Apache-2.0"]
keywords = ["Finance/Billing", "Cost/Paid"]
org = "ballerinax"
name = "ronin"
icon = "icon.png"
distribution = "2201.4.1"
repository = "https://github.com/ballerina-platform/openapi-connectors/tree/main/openapi/ronin"
version = "1.5.3"
authors = ["Ballerina"]
